# Generated by Django 5.2.15 on 2026-06-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Model1_MeteoBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mesure", models.DateTimeField(auto_now_add=True)),
                ("temperature", models.FloatField(help_text="En °C")),
                ("humidite", models.FloatField(help_text="En %")),
                ("vent", models.FloatField(help_text="En km/h")),
                ("precipitation", models.FloatField(help_text="En mm")),
            ],
        ),
        migrations.CreateModel(
            name="Model2_Rayonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mesure", models.DateTimeField(auto_now_add=True)),
                (
                    "rayonnement",
                    models.FloatField(help_text="Rayonnement solaire W/m²"),
                ),
                ("uv_index", models.FloatField(help_text="Indice UV 0-11+")),
            ],
        ),
        migrations.CreateModel(
            name="Model3_FWI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mesure", models.DateTimeField(auto_now_add=True)),
                ("fwi", models.FloatField(help_text="Fire Weather Index")),
            ],
        ),
        migrations.CreateModel(
            name="Model4_ET0",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mesure", models.DateTimeField(auto_now_add=True)),
                ("et0", models.FloatField(help_text="ET0 mm/jour")),
            ],
        ),
    ]
