# Generated by Django 5.2.15 on 2026-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model5_BatteriePyra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mesure", models.DateTimeField(auto_now_add=True)),
                ("tension", models.FloatField(help_text="Tension en Volts, ex: 3.7")),
                (
                    "pourcentage",
                    models.IntegerField(help_text="Niveau batterie 0 à 100%"),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("faible", "Batterie Faible"),
                            ("critique", "Critique"),
                        ],
                        default="ok",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Model2_Rayonnement",
        ),
        migrations.AddField(
            model_name="model1_meteobase",
            name="rayonnement",
            field=models.FloatField(
                blank=True, help_text="Rayonnement solaire W/m²", null=True
            ),
        ),
        migrations.AddField(
            model_name="model1_meteobase",
            name="uv_index",
            field=models.FloatField(blank=True, help_text="Indice UV 0-11+", null=True),
        ),
        migrations.AlterField(
            model_name="model1_meteobase",
            name="precipitation",
            field=models.FloatField(blank=True, help_text="En mm", null=True),
        ),
    ]
