# Generated by Django 4.2.29 on 2026-06-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0002_model5_batteriepyra_delete_model2_rayonnement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FWIDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Date")),
                (
                    "heure_mesure",
                    models.TimeField(default="12:00", verbose_name="Heure TU"),
                ),
                ("temp", models.FloatField(null=True, verbose_name="Temp 12h TU °C")),
                ("rh", models.FloatField(null=True, verbose_name="HR 12h TU %")),
                (
                    "wind_kmh",
                    models.FloatField(null=True, verbose_name="Vent 12h TU km/h"),
                ),
                ("rain_24h", models.FloatField(null=True, verbose_name="Pluie 24h mm")),
                ("fwi", models.FloatField(null=True, verbose_name="FWI")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="Model3_FWI",
        ),
    ]
