# Generated by Django 4.2.29 on 2026-06-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0003_fwidaily_delete_model3_fwi"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="model4_et0",
            options={"ordering": ["-date"], "verbose_name": "ET0 Journalier"},
        ),
        migrations.RemoveField(
            model_name="model4_et0",
            name="date_mesure",
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="date",
            field=models.DateField(
                blank=True, null=True, unique=True, verbose_name="Date"
            ),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="heure_mesure",
            field=models.TimeField(default="12:00", verbose_name="Heure TU"),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="radiation",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Rayonnement 12h TU W/m²"
            ),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="rh",
            field=models.FloatField(blank=True, null=True, verbose_name="HR 12h TU %"),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="temp",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Temp 12h TU °C"
            ),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="wind_kmh",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Vent 12h TU km/h"
            ),
        ),
        migrations.AlterField(
            model_name="model4_et0",
            name="et0",
            field=models.FloatField(blank=True, null=True, verbose_name="ET0 mm/jour"),
        ),
    ]
