# Generated by Django 4.2.29 on 2026-06-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0004_alter_model4_et0_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="model4_et0",
            name="heure_mesure",
        ),
        migrations.RemoveField(
            model_name="model4_et0",
            name="radiation",
        ),
        migrations.RemoveField(
            model_name="model4_et0",
            name="rh",
        ),
        migrations.RemoveField(
            model_name="model4_et0",
            name="temp",
        ),
        migrations.RemoveField(
            model_name="model4_et0",
            name="wind_kmh",
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="radiation_moy",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Rayonnement moyen (W/m²)"
            ),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="rh_moy",
            field=models.FloatField(
                blank=True, null=True, verbose_name="HR moyenne (%)"
            ),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="temp_moy",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Température moyenne (°C)"
            ),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="wind_moy",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Vent moyen (km/h)"
            ),
        ),
        migrations.AlterField(
            model_name="model4_et0",
            name="et0",
            field=models.FloatField(
                blank=True, null=True, verbose_name="ET0 (mm/jour)"
            ),
        ),
    ]
