# Generated by Django 4.2.29 on 2026-06-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0005_remove_model4_et0_heure_mesure_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Model2_Rayonnement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_mesure", models.DateTimeField(auto_now_add=True)),
                (
                    "rayonnement",
                    models.FloatField(help_text="Rayonnement solaire W/m²"),
                ),
            ],
        ),
    ]
