# Generated by Django 4.2.29 on 2026-06-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0006_model2_rayonnement"),
    ]

    operations = [
        migrations.AddField(
            model_name="fwidaily",
            name="date_calcul",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="model4_et0",
            name="date_calcul",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
