# Generated by Django 4.2.29 on 2026-06-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meteo", "0007_fwidaily_date_calcul_model4_et0_date_calcul"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandeLoRaWAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_commande", models.DateTimeField(auto_now_add=True)),
                ("equipement", models.CharField(max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("payload", models.CharField(max_length=50)),
                ("duree", models.IntegerField(blank=True, null=True)),
                ("statut", models.CharField(default="Préparée", max_length=50)),
            ],
        ),
    ]
